let vocabulary = [
  { ch: '爱', pin: 'ài', en: 'to love' },
  { ch: '八', pin: 'bā', en: 'eight' },
  { ch: '爸爸', pin: 'bàba', en: 'dad' },
  { ch: '杯子', pin: 'bēizi', en: 'cup' },
  { ch: '北京', pin: 'Běijīng', en: 'Beijing' },
  { ch: '本', pin: 'běn', en: 'book (classifier)' },
  { ch: '不客气', pin: 'bú kèqi', en: 'you’re welcome' },
  { ch: '不', pin: 'bù', en: 'not' },
  { ch: '菜', pin: 'cài', en: 'dish' },
  { ch: '茶', pin: 'chá', en: 'tea' },
  { ch: '车', pin: 'chē', en: 'vehicle' },
  { ch: '吃', pin: 'chī', en: 'to eat' },
  { ch: '出租车', pin: 'chūzūchē', en: 'taxi' },
  { ch: '打电话', pin: 'dǎ diànhuà', en: 'to call' },
  { ch: '大', pin: 'dà', en: 'big' },
  { ch: '大学', pin: 'dàxué', en: 'university' },
  { ch: '的', pin: 'de', en: 'possessive particle' },
  { ch: '点', pin: 'diǎn', en: 'o’clock' },
  { ch: '电话', pin: 'diànhuà', en: 'phone' },
  { ch: '电脑', pin: 'diànnǎo', en: 'computer' },
  { ch: '电视', pin: 'diànshì', en: 'television' },
  { ch: '电影', pin: 'diànyǐng', en: 'movie' },
  { ch: '弟弟', pin: 'dìdi', en: 'younger brother' },
  { ch: '东西', pin: 'dōngxi', en: 'thing' },
  { ch: '都', pin: 'dōu', en: 'all' },
  { ch: '读', pin: 'dú', en: 'to read' },
  { ch: '对不起', pin: 'duìbuqǐ', en: 'sorry' },
  { ch: '多', pin: 'duō', en: 'many' },
  { ch: '多少', pin: 'duōshao', en: 'how many' },
  { ch: '儿子', pin: 'érzi', en: 'son' },
  { ch: '二', pin: 'èr', en: 'two' },
  { ch: '饭', pin: 'fàn', en: 'food' },
  { ch: '饭店', pin: 'fàndiàn', en: 'restaurant' },
  { ch: '飞机', pin: 'fēijī', en: 'airplane' },
  { ch: '分钟', pin: 'fēnzhōng', en: 'minute' },
  { ch: '高兴', pin: 'gāoxìng', en: 'happy' },
  { ch: '个', pin: 'gè', en: 'general classifier' },
  { ch: '哥哥', pin: 'gēge', en: 'older brother' },
  { ch: '工作', pin: 'gōngzuò', en: 'to work' },
  { ch: '狗', pin: 'gǒu', en: 'dog' },
  { ch: '汉语', pin: 'Hànyǔ', en: 'Chinese language' },
  { ch: '汉字', pin: 'Hànzì', en: 'Chinese character' },
  { ch: '好', pin: 'hǎo', en: 'good' },
  { ch: '号', pin: 'hào', en: 'number' },
  { ch: '好吃', pin: 'hǎochī', en: 'delicious' },
  { ch: '喝', pin: 'hē', en: 'to drink' },
  { ch: '和', pin: 'hé', en: 'and' },
  { ch: '很', pin: 'hěn', en: 'very' },
  { ch: '后面', pin: 'hòumiàn', en: 'behind' },
  { ch: '回', pin: 'huí', en: 'to return' },
  { ch: '会', pin: 'huì', en: 'can' },
  { ch: '火', pin: 'huǒ', en: 'fire' },
  { ch: '火车', pin: 'huǒchē', en: 'train' },
  { ch: '火车站', pin: 'huǒchēzhàn', en: 'train station' },
  { ch: '几', pin: 'jǐ', en: 'how many' },
  { ch: '家', pin: 'jiā', en: 'home' },
  { ch: '叫', pin: 'jiào', en: 'to be called' },
  { ch: '姐姐', pin: 'jiějie', en: 'older sister' },
  { ch: '今年', pin: 'jīnnián', en: 'this year' },
  { ch: '今天', pin: 'jīntiān', en: 'today' },
  { ch: '九', pin: 'jiǔ', en: 'nine' },
  { ch: '开', pin: 'kāi', en: 'to open' },
  { ch: '看见', pin: 'kànjiàn', en: 'to see' },
  { ch: '课', pin: 'kè', en: 'lesson' },
  { ch: '块', pin: 'kuài', en: 'piece' },
  { ch: '快乐', pin: 'kuàilè', en: 'happy' },
  { ch: '来', pin: 'lái', en: 'to come' },
  { ch: '老师', pin: 'lǎoshī', en: 'teacher' },
  { ch: '了', pin: 'le', en: 'past particle' },
  { ch: '冷', pin: 'lěng', en: 'cold' },
  { ch: '里面', pin: 'lǐmiàn', en: 'inside' },
  { ch: '两', pin: 'liǎng', en: 'two (used for counting)' },
  { ch: '零', pin: 'líng', en: 'zero' },
  { ch: '六', pin: 'liù', en: 'six' },
  { ch: '妈妈', pin: 'māma', en: 'mom' },
  { ch: '吗', pin: 'ma', en: 'question particle' },
  { ch: '买', pin: 'mǎi', en: 'to buy' },
  { ch: '猫', pin: 'māo', en: 'cat' },
  { ch: '没', pin: 'méi', en: 'not' },
  { ch: '妹妹', pin: 'mèimei', en: 'younger sister' },
  { ch: '美国', pin: 'Měiguó', en: 'United States' },
  { ch: '没关系', pin: 'méi guānxi', en: 'it doesn’t matter' },
  { ch: '面条', pin: 'miàntiáo', en: 'noodles' },
  { ch: '米饭', pin: 'mǐfàn', en: 'rice' },
  { ch: '明天', pin: 'míngtiān', en: 'tomorrow' },
  { ch: '名字', pin: 'míngzi', en: 'name' },
    { ch: '哪个', pin: 'nǎge', en: 'which' },
  { ch: '哪儿', pin: 'nǎr', en: 'where' },
  { ch: '那(个)', pin: 'nà', en: 'that' },
  { ch: '那儿', pin: 'nàr', en: 'there' },
  { ch: '呢', pin: 'ne', en: 'present particle' },
  { ch: '能', pin: 'néng', en: 'to be able to' },
  { ch: '你', pin: 'nǐ', en: 'you' },
  { ch: '你们', pin: 'nǐmen', en: 'you (plural)' },
  { ch: '您', pin: 'nín', en: 'you (polite)' },
  { ch: '您们', pin: 'nínmen', en: 'you (polite, plural)' },
  { ch: '年', pin: 'nián', en: 'year' },
  { ch: '女儿', pin: 'nǚ’ér', en: 'daughter' },
  { ch: '朋友', pin: 'péngyou', en: 'friend' },
  { ch: '漂亮', pin: 'piàoliang', en: 'beautiful' },
  { ch: '苹果', pin: 'píngguǒ', en: 'apple' },
  { ch: '七', pin: 'qī', en: 'seven' },
  { ch: '钱', pin: 'qián', en: 'money' },
  { ch: '前面', pin: 'qiánmiàn', en: 'in front' },
  { ch: '请', pin: 'qǐng', en: 'please' },
  { ch: '请问', pin: 'qǐngwèn', en: 'excuse me' },
  { ch: '去', pin: 'qù', en: 'to go' },
  { ch: '热', pin: 'rè', en: 'hot' },
  { ch: '人', pin: 'rén', en: 'person' },
  { ch: '认识', pin: 'rènshi', en: 'to know' },
  { ch: '日', pin: 'rì', en: 'day' },
  { ch: '三', pin: 'sān', en: 'three' },
  { ch: '商店', pin: 'shāngdiàn', en: 'shop' },
  { ch: '上面', pin: 'shàngmiàn', en: 'above' },
  { ch: '上午', pin: 'shàngwǔ', en: 'morning' },
  { ch: '少', pin: 'shǎo', en: 'few' },
  { ch: '谁', pin: 'shéi', en: 'who' },
  { ch: '什么', pin: 'shénme', en: 'what' },
  { ch: '什么时候', pin: 'shénme shíhou', en: 'when' },
  { ch: '身体', pin: 'shēntǐ', en: 'body' },
  { ch: '十', pin: 'shí', en: 'ten' },
  { ch: '是', pin: 'shì', en: 'to be' },
  { ch: '时候', pin: 'shíhou', en: 'time' },
  { ch: '书', pin: 'shū', en: 'book' },
  { ch: '书店', pin: 'shūdiàn', en: 'bookshop' },
  { ch: '水', pin: 'shuǐ', en: 'water' },
  { ch: '水果', pin: 'shuǐguǒ', en: 'fruit' },
  { ch: '睡觉', pin: 'shuìjiào', en: 'to sleep' },
  { ch: '说话', pin: 'shuōhuà', en: 'to speak' },
  { ch: '四', pin: 'sì', en: 'four' },
  { ch: '岁', pin: 'suì', en: 'years old' },
  { ch: '他', pin: 'tā', en: 'he' },
  { ch: '她', pin: 'tā', en: 'she' },
  { ch: '它', pin: 'tā', en: 'it' },
  { ch: '他们', pin: 'tāmen', en: 'they' },
  { ch: '太', pin: 'tài', en: 'too' },
  { ch: '天', pin: 'tiān', en: 'day' },
  { ch: '天气', pin: 'tiānqì', en: 'weather' },
  { ch: '听见', pin: 'tīngjiàn', en: 'to hear' },
  { ch: '同学', pin: 'tóngxué', en: 'classmate' },
  { ch: '王', pin: 'Wáng', en: 'surname Wang' },
  { ch: '问', pin: 'wèn', en: 'to ask' },
  { ch: '我', pin: 'wǒ', en: 'I' },
  { ch: '我们', pin: 'wǒmen', en: 'we' },
  { ch: '五', pin: 'wǔ', en: 'five' },
  { ch: '喜欢', pin: 'xǐhuan', en: 'to like' },
  { ch: '下面', pin: 'xiàmiàn', en: 'below' },
  { ch: '下午', pin: 'xiàwǔ', en: 'afternoon' },
  { ch: '下雨', pin: 'xiàyǔ', en: 'to rain' },
  { ch: '先生', pin: 'xiānsheng', en: 'Mr.' },
  { ch: '现在', pin: 'xiànzài', en: 'now' },
  { ch: '想', pin: 'xiǎng', en: 'to think' },
  { ch: '小', pin: 'xiǎo', en: 'small' },
  { ch: '小姐', pin: 'xiǎojiě', en: 'Miss' },
  { ch: '西班牙', pin: 'Xībānyá', en: 'Spain' },
  { ch: '些', pin: 'xiē', en: 'some' },
  { ch: '写', pin: 'xiě', en: 'to write' },
  { ch: '谢谢', pin: 'xièxie', en: 'thank you' },
  { ch: '心', pin: 'xīn', en: 'heart' },
  { ch: '星期', pin: 'xīngqī', en: 'week' },
  { ch: '学', pin: 'xué', en: 'to study' },
  { ch: '学生', pin: 'xuésheng', en: 'student' },
  { ch: '学习', pin: 'xuéxí', en: 'to study' },
  { ch: '学校', pin: 'xuéxiào', en: 'school' },
  { ch: '也', pin: 'yě', en: 'also' },
  { ch: '一', pin: 'yī', en: 'one' },
  { ch: '衣服', pin: 'yīfu', en: 'clothes' },
  { ch: '一会儿', pin: 'yíhuìr', en: 'a moment' },
  { ch: '一起', pin: 'yìqǐ', en: 'together' },
  { ch: '医生', pin: 'yīshēng', en: 'doctor' },
  { ch: '医院', pin: 'yīyuàn', en: 'hospital' },
  { ch: '椅子', pin: 'yǐzi', en: 'chair' },
  { ch: '有', pin: 'yǒu', en: 'to have' },
  { ch: '月', pin: 'yuè', en: 'month' },
  { ch: '在', pin: 'zài', en: 'to be at' },
  { ch: '再见', pin: 'zàijiàn', en: 'goodbye' },
  { ch: '怎么', pin: 'zěnme', en: 'how' },
  { ch: '怎么样', pin: 'zěnmeyàng', en: 'how is it' },
  { ch: '这个', pin: 'zhège', en: 'this' },
  { ch: '这么', pin: 'zhème', en: 'so' },
  { ch: '这儿', pin: 'zhèr', en: 'here' },
    { ch: '中国', pin: 'Zhōngguó', en: 'China' },
  { ch: '中午', pin: 'zhōngwǔ', en: 'noon' },
  { ch: '住', pin: 'zhù', en: 'to live' },
  { ch: '桌子', pin: 'zhuōzi', en: 'table' },
  { ch: '字', pin: 'zì', en: 'character' },
  { ch: '昨天', pin: 'zuótiān', en: 'yesterday' },
  { ch: '坐', pin: 'zuò', en: 'to sit' },
  { ch: '做', pin: 'zuò', en: 'to do' },
  { ch: '零', pin: 'líng', en: 'zero' },
  { ch: '幺', pin: 'yāo', en: 'one (in phone numbers)' },
  { ch: '两', pin: 'liǎng', en: 'two (used in counting)' },
  { ch: '三', pin: 'sān', en: 'three' },
  { ch: '四', pin: 'sì', en: 'four' },
  { ch: '五', pin: 'wǔ', en: 'five' },
  { ch: '六', pin: 'liù', en: 'six' },
  { ch: '七', pin: 'qī', en: 'seven' },
  { ch: '八', pin: 'bā', en: 'eight' },
  { ch: '九', pin: 'jiǔ', en: 'nine' },
  { ch: '十', pin: 'shí', en: 'ten' }
];