const voclists = [
  { filename: "H1L1a4", title: "HSK 1 Lessons 1 to 4", level: "H1", misc: "MIT" },
  { filename: "H1L5", title: "HSK 1 Lesson 5", level: "H1", misc: "MIT" },
  { filename: "H1L5a6", title: "HSK 1 Lessons 5 & 6", level: "H1", misc: "MIT" },
  { filename: "H1L1a6", title: "HSK 1 Lessons 1 to 6", level: "H1", misc: "MIT" },
  { filename: "H1L7", title: "HSK 1 Lesson 7", level: "H1", misc: "MIT" },
  { filename: "H1L8", title: "HSK 1 Lesson 8", level: "H1", misc: "MIT" },
  { filename: "H1L6a8", title: "HSK 1 Lessons 6 to 8", level: "H1", misc: "MIT" },
  { filename: "H1L13", title: "HSK 1 Lesson 13", level: "H1", misc: "MIT" },
  { filename: "H1L14", title: "HSK 1 Lesson 14", level: "H1", misc: "MIT" },
  { filename: "H1L14a15", title: "HSK 1 Lessons 14 & 15", level: "H1", misc: "MIT" },
  { filename: "H1L16", title: "HSK 1 Lesson 16 Wb", level: "H1", misc: "MIT" },
  { filename: "H1E110034", title: "HSK 1 H11003/4 Vocabulary", level: "H1", misc: "MIT" },
  { filename: "hsk1", title: "HSK 1 Vocabulary (full)", level: "H1", misc: "hsk" },
  { filename: "H2L1a3", title: "HSK 2 Lessons 1 to 3", level: "H2", misc: "MIT" },
  { filename: "hsk2", title: "HSK 2 Vocabulary (full)", level: "H2", misc: "hsk" },
  { filename: "H3L1", title: "HSK 3 Lesson 1", level: "H3", misc: "MIT" },
  { filename: "hsk3", title: "HSK 3 Vocabulary (full)", level: "H3", misc: "hsk" },
  { filename: "viajes", title: "Travelling in Chinese", level: "H2", misc: "topics" },
  { filename: "house", title: "The house", level: "H3", misc: "topics" },
  // más listados...
];
