let vocabulary = [
{ ch: '阿姨', pin: 'āyí', en: 'tía' },
{ ch: '爱', pin: 'ài', en: 'amar' },
{ ch: '八', pin: 'bā', en: 'ocho' },
{ ch: '爸爸', pin: 'bàba', en: 'papá' },
{ ch: '杯子', pin: 'bēizi', en: 'vaso' },
{ ch: '北京', pin: 'Běijīng', en: 'Pekín' },
{ ch: '本', pin: 'běn', en: 'clasificador libros' },
{ ch: '不客气', pin: 'búkeqì', en: 'de nada' },
{ ch: '不', pin: 'bù', en: 'no' },
{ ch: '菜', pin: 'cài', en: 'plato' },
{ ch: '茶', pin: 'chá', en: 'té' },
{ ch: '吃', pin: 'chī', en: 'comer' },
{ ch: '出租车', pin: 'chūzūchē', en: 'taxi' },
{ ch: '打 电话', pin: 'dǎdiànhuà', en: 'telefonear' },
{ ch: '大', pin: 'dà', en: 'grande' },
{ ch: '的', pin: 'de', en: 'partícula' },
{ ch: '点', pin: 'diǎn', en: 'punto' },
{ ch: '电脑', pin: 'diànnǎo', en: 'ordenador' },
{ ch: '电视', pin: 'diànshì', en: 'televisor' },
{ ch: '电影', pin: 'diànyǐng', en: 'película' },
{ ch: '东西', pin: 'dōngxi', en: 'cosa' },
{ ch: '都', pin: 'dōu', en: 'todo' },
{ ch: '读', pin: 'dú', en: 'leer' },
{ ch: '对不起', pin: 'duìbuqǐ', en: 'Lo siento' },
{ ch: '多', pin: 'duō', en: 'mucho' },
{ ch: '多少', pin: 'duōshǎo', en: 'cuánto' },
{ ch: '儿子', pin: 'érzi', en: 'hijo' },
{ ch: '二', pin: 'èr', en: 'dos' },
{ ch: '飞机', pin: 'fēijī', en: 'avión' },
{ ch: '高兴', pin: 'gāoxìng', en: 'encantado' },
{ ch: '个', pin: 'gè', en: 'cada' },
{ ch: '工作', pin: 'gōngzuò', en: 'trabajo' },
{ ch: '狗', pin: 'gǒu', en: 'perro' },
{ ch: '汉语', pin: 'Hànyǔ', en: 'chino' },
{ ch: '好', pin: 'hǎo', en: 'bueno' },
{ ch: '喝', pin: 'hē', en: 'beber' },
{ ch: '和', pin: 'hé', en: 'y' },
{ ch: '很', pin: 'hěn', en: 'muy' },
{ ch: '后面', pin: 'hòumian', en: 'detrás' },
{ ch: '回', pin: 'huí', en: 'regresar' },
{ ch: '会', pin: 'huì', en: 'futuro saber' },
{ ch: '火车站', pin: 'huǒchēzhàn', en: 'estación de tren' },
{ ch: '几', pin: 'jǐ', en: 'varios cuántos' },
{ ch: '家', pin: 'jiā', en: 'familia' },
{ ch: '今天', pin: 'jīntiān', en: 'hoy' },
{ ch: '九', pin: 'jiǔ', en: 'nueve' },
{ ch: '开', pin: 'kāi', en: 'abrir' },
{ ch: '看', pin: 'kàn', en: 'ver' },
{ ch: '看见', pin: 'kànjiàn', en: 'mirar' },
{ ch: '块', pin: 'kuài', en: 'pedazo' },
{ ch: '快', pin: 'kuài', en: 'rápido' },
{ ch: '来', pin: 'lái', en: 'venir' },
{ ch: '老师', pin: 'lǎoshī', en: 'maestro' },
{ ch: '了', pin: 'le', en: 'pasado' },
{ ch: '冷', pin: 'lěng', en: 'frío' },
{ ch: '里', pin: 'lǐ', en: 'dentro' },
{ ch: '零', pin: 'líng', en: 'cero' },
{ ch: '六', pin: 'liù', en: 'seis' },
{ ch: '妈妈', pin: 'māma', en: 'mama' },
{ ch: '马', pin: 'mǎ', en: 'caballo' },
{ ch: '买', pin: 'mǎi', en: 'comprar' },
{ ch: '猫', pin: 'māo', en: 'gato' },
{ ch: '没', pin: 'méi', en: 'no' },
{ ch: '没关系', pin: 'méiguānxi', en: 'No importa' },
{ ch: '米饭', pin: 'mǐfàn', en: 'arroz' },
{ ch: '明天', pin: 'míngtiān', en: 'mañana' },
{ ch: '名字', pin: 'míngzi', en: 'nombre' },
{ ch: '哪', pin: 'nǎ', en: 'dónde' },
{ ch: '那', pin: 'nà', en: 'ese' },
{ ch: '呢', pin: 'ne', en: 'partícula preguntas' },
{ ch: '能', pin: 'néng', en: 'poder' },
{ ch: '你', pin: 'nǐ', en: 'tú' },
{ ch: '年', pin: 'nián', en: 'año' },
{ ch: '女儿', pin: 'nǚér', en: 'hija' },
{ ch: '朋友', pin: 'péngyǒu', en: 'amigo' },
{ ch: '苹果', pin: 'píngguǒ', en: 'manzana' },
{ ch: '七', pin: 'qī', en: 'siete' },
{ ch: '钱', pin: 'qián', en: 'dinero' },
{ ch: '前面', pin: 'qiánmiàn', en: 'delante' },
{ ch: '请', pin: 'qǐng', en: 'por favor' },
{ ch: '去', pin: 'qù', en: 'ir' },
{ ch: '热', pin: 'rè', en: 'calor' },
{ ch: '人', pin: 'rén', en: 'persona' },
{ ch: '认识', pin: 'rènshi', en: 'conocer' },
{ ch: '日', pin: 'rì', en: 'día' },
{ ch: '三', pin: 'sān', en: 'tres' },
{ ch: '商店', pin: 'shāngdiàn', en: 'tienda' },
{ ch: '上', pin: 'shàng', en: 'arriba' },
{ ch: '上午', pin: 'shàngwǔ', en: 'por la mañana' },
{ ch: '少', pin: 'shǎo', en: 'poco' },
{ ch: '谁', pin: 'shéi', en: 'quién' },
{ ch: '什么', pin: 'shénme', en: 'qué' },
{ ch: '十', pin: 'shí', en: 'diez' },
{ ch: '时候', pin: 'shíhou', en: 'después' },
{ ch: '是', pin: 'shì', en: 'ser' },
{ ch: '书', pin: 'shū', en: 'libro' },
{ ch: '水', pin: 'shuǐ', en: 'agua' },
{ ch: '水果', pin: 'shuǐguǒ', en: 'fruta' },
{ ch: '睡觉', pin: 'shuìjiào', en: 'dormir' },
{ ch: '说话', pin: 'shuōhuà', en: 'hablar' },
{ ch: '四', pin: 'sì', en: 'cuatro' },
{ ch: '岁', pin: 'suì', en: 'año de edad' },
{ ch: '他', pin: 'tā', en: 'él' },
{ ch: '她', pin: 'tā', en: 'ella' },
{ ch: '太', pin: 'tài', en: 'demasiado' },
{ ch: '天气', pin: 'tiānqì', en: 'tiempo climático' },
{ ch: '听', pin: 'tīng', en: 'escuchar' },
{ ch: '同学', pin: 'tóngxué', en: 'compañero de clase' },
{ ch: '我', pin: 'wǒ', en: 'yo' },
{ ch: '我们', pin: 'wǒmen', en: 'nosotros' },
{ ch: '五', pin: 'wǔ', en: 'cinco' },
{ ch: '喜欢', pin: 'xǐhuan', en: 'gustar' },
{ ch: '下', pin: 'xià', en: 'abajo' },
{ ch: '下午', pin: 'xiàwǔ', en: 'por la tarde' },
{ ch: '下雨', pin: 'xiàyǔ', en: 'llover' },
{ ch: '先生', pin: 'xiānsheng', en: 'señor' },
{ ch: '现在', pin: 'xiànzài', en: 'ahora' },
{ ch: '想', pin: 'xiǎng', en: 'desear' },
{ ch: '小', pin: 'xiǎo', en: 'pequeño' },
{ ch: '小姐', pin: 'xiǎojiě', en: 'señorita' },
{ ch: '些', pin: 'xiē', en: 'algunos' },
{ ch: '写', pin: 'xiě', en: 'escribir' },
{ ch: '谢谢', pin: 'xièxie', en: 'gracias' },
{ ch: '星期', pin: 'xīngqī', en: 'semana' },
{ ch: '学生', pin: 'xuésheng', en: 'estudiante' },
{ ch: '学习', pin: 'xuéxí', en: 'aprender' },
{ ch: '学校', pin: 'xuéxiào', en: 'escuela' },
{ ch: '一', pin: 'yī', en: 'uno' },
{ ch: '衣服', pin: 'yīfu', en: 'ropa' },
{ ch: '医生', pin: 'yīshēng', en: 'médico' },
{ ch: '医院', pin: 'yīyuàn', en: 'hospital' },
{ ch: '椅子', pin: 'yǐzi', en: 'silla' },
{ ch: '有', pin: 'yǒu', en: 'tener haber' },
{ ch: '月', pin: 'yuè', en: 'mes' },
{ ch: '在', pin: 'zài', en: 'en' },
{ ch: '再见', pin: 'zài jiàn', en: 'adiós' },
{ ch: '怎么', pin: 'zěnme', en: 'cómo' },
{ ch: '怎么样', pin: 'zěnmeyàng', en: 'qué tal' },
{ ch: '这', pin: 'zhè', en: 'este' },
{ ch: '中国', pin: 'Zhōngguó', en: 'China' },
{ ch: '中午', pin: 'zhōngwǔ', en: 'mediodía' },
{ ch: '住', pin: 'zhù', en: 'vivir' },
{ ch: '桌子', pin: 'zhuōzi', en: 'mesa' },
{ ch: '字', pin: 'zì', en: 'letra' },
{ ch: '昨天', pin: 'zuótiān', en: 'ayer' },
{ ch: '坐', pin: 'zuò', en: 'sentarse' },
{ ch: '做', pin: 'zuò', en: 'hacer' }
];